name: CI
on:
  pull_request:
    branches: ['develop', 'main']

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        run: npm i install

      - name: Lint
        run: npm run lint

      - name: Set Environment Variables
        run: |
          echo "DB_USER=$DB_USER" >> $GITHUB_ENV
          echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV
          echo "DB_DIALECT=$DB_DIALECT" >> $GITHUB_ENV

      - name: Test
        run: npm run test
