name: CI
on:
  pull_request:
    branches: ['develop', 'main']

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        run: npm i install

      - name: Lint
        run: npm run lint

      - name: Check PostgreSQL status
        run: |
          if service postgresql status; then
            echo "PostgreSQL is running."
          else
            echo "PostgreSQL is not running. Starting PostgreSQL..."
            systemctl start postgresql
          fi

      - name: Test
        run: npm run test
